version: '{build}'

platform: x86
configuration: Release

build: 
    project: WindBot.sln
    parallel: true

after_build:
  - mv -f bin\Release WindBot
  - rm -rf WindBot\WindBot.exe.config
  - mv -f BotWrapper\bin\Release\Bot.exe .
  - mv -f BotWrapper\bin\Release\bot.conf .
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/purerosefallen/ygopro-7210srv/raw/master/cards.cdb ; exit 0"
  - mv -f cards.cdb WindBot
  - 7z a -mx9 WindBot.7z WindBot Bot.exe bot.conf
  
test_script:
- cd WindBot
- WindBot.exe Name=Clala Host=118.178.111.167 Port=233 Version=4929 Deck=Nekroz
- cd ..

artifacts:
  - path: WindBot.7z
    name: WindBot

