version: '{build}'
skip_tags: true

install:
- mkdir WindBot
  
configuration: Release

build: 
    project: Windbot.sln
    parallel: true
    output: ./WindBot

after_build:
  - git config --global user.name "Smile-DK"
  - git config --global user.email "2236141431@qq.com"
  
  - cp -rf bin/x86/Release/* WindBot
  - git clone https://github.com/moecube/ygopro-database
  - cp -rf ygopro-database/locales/zh-CN/cards.cdb WindBot
  - git clone https://github.com/Smile-DK/ygopro-svrelease
  - cd ygopro-svrelease
  - rm -rf WindBot
  - cp -rf ../WindBot .
  - git add . -A
  - git commit -m "Windbot pushed by Appveyor"
  - git push %Smile%Smile-DK/ygopro-svrelease master
  - cd ..
  - 7z a WindBot.7z WindBot
test: off

artifacts:
  - path: WindBot.7z
    name: WindBot
branches:
  only:
    - master

